name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/6 * * * *'  # Runs every 5 minutes
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the fork repository
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to avoid issues

      # Set up Git
      - name: Set up Git
        uses: actions/setup-git@v2

      # Add the upstream remote
      - name: Add upstream remote
        run: git remote add upstream https://github.com/d-cdmi/managment.git

      # Fetch changes from upstream
      - name: Fetch upstream
        run: git fetch upstream

      # Checkout the main branch of your fork
      - name: Checkout main branch
        run: git checkout main

      # Merge changes from upstream into your fork's main branch
      - name: Merge upstream changes into fork
        run: |
          git merge upstream/main --no-edit || exit 0  # Continue even if there are conflicts

      # Push the changes to your fork
      - name: Push changes to fork
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
